###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlhdCI6MTY0Njg3Nzc4MiwiZXhwIjoxNjQ2ODgxMzgyfQ.J9uSGS2KjLR4FGWBxexTKVHC0vUurHuizoxAUz3YWXs

{
    "title": "sample",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlhdCI6MTY0NjcwNzUyNSwiZXhwIjoxNjQ2NzExMTI1fQ.rQxdSg4XDaMVtfQOjtKgIcfgaOY6Q-iAqov7zk39Cjk

{
    "title": "",
    "description": ""
}

###
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlhdCI6MTY0Njg3Nzc4MiwiZXhwIjoxNjQ2ODgxMzgyfQ.J9uSGS2KjLR4FGWBxexTKVHC0vUurHuizoxAUz3YWXs
###
GET http://localhost:3000/tasks?status=IN_PROGRESS

###
GET http://localhost:3000/tasks?search=WED

###
GET http://localhost:3000/tasks/d6f73496-96b5-45a6-b950-40f3f864eef7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlhdCI6MTY0Njg3Nzc4MiwiZXhwIjoxNjQ2ODgxMzgyfQ.J9uSGS2KjLR4FGWBxexTKVHC0vUurHuizoxAUz3YWXs

###
DELETE http://localhost:3000/tasks/b68a1671-f697-4673-9830-58d1ce02b364
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlhdCI6MTY0Njg3Nzc4MiwiZXhwIjoxNjQ2ODgxMzgyfQ.J9uSGS2KjLR4FGWBxexTKVHC0vUurHuizoxAUz3YWXs
###
PATCH http://localhost:3000/tasks/f114f4c1-2ab3-4e4e-9f30-1ac0de95b947/status HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlhdCI6MTY0Njg3Nzc4MiwiZXhwIjoxNjQ2ODgxMzgyfQ.J9uSGS2KjLR4FGWBxexTKVHC0vUurHuizoxAUz3YWXs

{
    "status": "IN_PROGRESS"
}

###
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "username2",
    "password": "ApjopPq89i"
}


###
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "username": "username2",
    "password": "ApjopPq89i"
}

###
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "username2",
    "password": "ApjopPq89ia"
}


###
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "username",
    "password": "ApjopPq89i"
}

###
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "username",
    "password": "ApjopPq89i"
}