###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "",
    "description": ""
}

###
GET http://localhost:3000/tasks

###
GET http://localhost:3000/tasks?status=IN_PROGRESS

###
GET http://localhost:3000/tasks?search=WED

###
GET http://localhost:3000/tasks/6dc8a582-bffe-43e1-ba12-22a61cd734ac

###
DELETE http://localhost:3000/tasks/35af5e3c-6e9b-44ea-8c10-17535a35a749

###
PATCH http://localhost:3000/tasks/f114f4c1-2ab3-4e4e-9f30-1ac0de95b947/status HTTP/1.1
content-type: application/json

{
    "status": "IN_PROGRESS"
}

###
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "username2",
    "password": "ApjopPq89i"
}

###
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "username2",
    "password": "ApjopPq89ia"
}
