###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
GET http://localhost:3000/tasks

###
GET http://localhost:3000/tasks/6dc8a582-bffe-43e1-ba12-22a61cd734ac

###
DELETE http://localhost:3000/tasks/98d56652-a41c-4e59-af6c-ad306436af42