name: Deploy

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn

      - name: Install dependencies
        run: yarn lint

      - name: Install dependencies
        run: yarn format

      - name: Build React App
        run: yarn build
        env:
          HTTPS: 'true'
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

